version: "3.8"

services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: vladimir
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: training_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

volumes:
  postgres_data: